### ISSUE TITLE
Rust panic when using large number of layers

### ISSUE THREAD

**Issue by os-gabe** [granne/granne#5]
When running the `build_and_search.py` example I get the following error after changing the configuration to 
```
DIM = 256
NUM_VECTORS = 100000
NUM_LAYERS = 100
```

```
Saving to disk
thread '<unnamed>' panicked at 'assertion failed: metadata.len() <= METADATA_LEN', /tmp/pip-req-build-xonb6jzo/src/hnsw/io.rs:71:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::begin_panic
  12: granne::hnsw::io::save_index_to_disk
  13: granne::hnsw::HnswBuilder<Elements,Element>::save_index_to_disk
  14: granne::HnswBuilder::save_index
  15: cpython::objects::string::<impl cpython::conversion::RefFromPyObject for str>::with_extracted
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  18: cpython::function::handle_callback
  19: granne::HnswBuilder::create_instance::init::wrap_instance_method
  20: PyCFunction_Call
  21: PyEval_EvalFrameEx
  22: <unknown>
  23: PyEval_EvalCode
  24: <unknown>
  25: PyRun_FileExFlags
  26: PyRun_SimpleFileExFlags
  27: Py_Main
  28: main
  29: __libc_start_main
  30: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "examples/py/build_and_search.py", line 32, in <module>
    builder.save_index(INDEX_PATH)
SystemError: Rust panic
```
I guess a separate question is how to choose an appropriate number of layers.

**Comment by os-gabe** [comment]
A binary search showed that the issue occurs with `NUM_LAYERS > 89` and does not with `NUM_LAYERS <= 89` (holding other parameters constant).

**Comment by erik-cliqz** [comment]
As you can see here https://github.com/granne/granne/blob/master/src/hnsw/mod.rs#L654-L658, the number of layers decides the `layer_multiplier`, i.e., the overlap between layers or, more precisely, the factor with which the number of elements in a layer increases as you go through the layers. (The `layer_multiplier` is related to the `mL` parameter in the original paper.) In other words, with a `layer_multiplier` of 10, the first layer has 1 element, the second 10, the third, 100, etc.

When you set `num_layers` to 100 (which is very high), it means that the layer multiplier gets really small (around ~1.1), and in turn you will have many layers that look the same. So I would not call this a bug, but I agree that the error message could be nicer.

Now, how does one choose the number of layers? I don't have much empirical evidence for this, but you could try aiming for a `layer_multiplier` of 10-30. Normally, you would try something in the range of 5-15 layers.

I am aware that `num_layers` is more difficult to work with than `layer_multiplier`, since the latter depends a lot on the number of elements. This is something I plan on changing in future version.

Hope this helps!
